amcl:
  ros__parameters:
    use_sim_time: true
    min_particles: 200
    max_particles: 2000
    laser_max_range: 3.5

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "~/maze_map.yaml"

bt_navigator:
  ros__parameters:
    use_sim_time: true

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.1

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      goal_checker_plugins: ["general_goal_checker"]
      general_goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.05
        yaw_goal_tolerance: 0.05

smoother_server:
  ros__parameters:
    use_sim_time: true

recoveries_server:
  ros__parameters:
    use_sim_time: true

behavior_server:
  ros__parameters:
    use_sim_time: true
